/* This file was generated by syncqt. */
#ifndef QT_QT3DINPUT_VERSION_H
#define QT_QT3DINPUT_VERSION_H

#define QT3DINPUT_VERSION_STR "5.11.3"

#define QT3DINPUT_VERSION 0x050B03

#endif // QT_QT3DINPUT_VERSION_H
